### ISSUE TITLE
"Server Not Booted" in a sea of errors

### ISSUE THREAD

**Issue by kfrncs** [belangeo/pyo#130]
Hi, no clue how to proceed on this:

In [3]: s = Server().boot()
ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
Cannot lock down 82280346 byte memory area (Cannot allocate memory)
Pyo warning: Portaudio input device `HDA Intel PCH: HDMI 0 (hw:0,3)` has fewer channels (0) than requested (2).
Portaudio error in Pa_OpenStream: Invalid number of channels
Pyo error: From portaudio, Invalid number of channels
Portaudio error in Pa_CloseStream (pa_deinit): PortAudio not initialized
Portaudio error in Pa_Terminate (pa_deinit): PortAudio not initialized
Pyo error: 
Server not booted.
Pyo warning: Portmidi warning: could not open midi input 1 (Midi Through Port-0): PortMidi: `Invalid device ID'
Pyo warning: Portmidi warning: could not open midi output 0 (Midi Through Port-0): PortMidi: `Invalid device ID'
Pyo warning: Portmidi closed.

**Comment by belangeo** [comment]
Hi,

You can safely ignore ALSA warning. The real problem is that you are trying to create a Server in duplex mode (both input and output, which is the default) but your audio device (HDMI) does not have any input. You can:

1. turn off duplex mode with duplex=0 as Server argument
2. Change your system's default audio device to something that have both inputs and outputs
3. Change the audio device used by the Server with setInOutDevice(x) method.
4. Use jack!

As for the portmidi warning, I really don't know why portmidi can't open Midi Through Port-0 but unless you need MIDI control, this one can also be ignored.

**Comment by mirh** [comment]
Microphone has nothing to do with this. 
The server fails to boot if you have no physical output connected. 

This is different from windows, where only disabling the "render" device altogether makes everything fail badly (with a crash btw nonetheless)

**Comment by belangeo** [comment]
> Microphone has nothing to do with this.
> The server fails to boot if you have no physical output connected.

Nope, the server does not fail to boot if no physical output is connected (actually the server never know *if* there is a physical output connected), it only connects to input/output ports. The problem here is a mismatch in number of channels, as state by:

> Pyo warning: Portaudio input device HDA Intel PCH: HDMI 0 (hw:0,3) has fewer channels (0) than requested (2).

So, disabling duplex (`duplex=0`) should be just fine.

**Comment by mirh** [comment]
I'm stating the aforementioned, because that was indeed my experience with Xubuntu 16.04

**Comment by belangeo** [comment]
Well, is there a computer that don't even have a builtin audio output?

But in the OP case discussed here, it is clearly the input number of channels mismatch that prevent the server from booting...

**Comment by mirh** [comment]
> Well, is there a computer that don't even have a builtin audio output?

I mean, putting aside that I don't see why not, what I'm telling here is that until I plugged in the speakers to my desktop, the server couldn't even start. 
(and, with the exception of the onboard realtek being mentioned in place of HDMI, the error message was the same)

**Comment by belangeo** [comment]
That is weird because pyo does not (and can't) have any idea if something is plugged or not... I suppose that plugging the speakers activate a switch in the system's audio management...

**Comment by mirh** [comment]
That was also my impression (I think `pactl` was showing 1 sink and 0 outputs, or viceversa, before I plugged in the thing, 1 and 2 afterwards). 
Still, something to take into consideration.

**Comment by mirh** [comment]
[This](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1602635968018085240) gave me an idea. 
It may be that until the very ***first*** time you connect \*anything\* to the computer, pulseaudio has no output set by default at all. 
Because indeed, now I don't get the sea of errors anymore even without any device, just the usual
```
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
```
