### ISSUE TITLE
Unsynchronized oscillator with MidiAdsr attack

### ISSUE THREAD

**Issue by vallsv** [belangeo/pyo#157]
Hi,

I use `MidiAdsr` together with 3 de-tuned oscillators.

```
notes = Notein(poly=10, scale=0, first=0, last=127, channel=0, mul=1)
freqs = MToF(notes["pitch"])
env = MidiAdsr(notes['velocity'])
lfo = LFO(freq=freqs, mul=env)
lfo2 = LFO(freq=freqs * (1 + 0.0052), mul=env * (6./7))
lfo3 = LFO(freq=freqs * (1 + 0.0102), mul=env * (3./4))
mix = Mix([lfo, lfo2, lfo3], mul=0.1)
mix..mix(1).out()
```

Not sure about what i say, but as i understand, this oscillators make there own life, and the midi signal is used to apply an envelope at the right time.

This way, i feel that there is no way to synchronize the oscillator at a time with a specific phase. How can i do if i want to reproduce the same sound anyway the timing. Is there a way to do that? Or i have to manage MIDI input by myself?

Thanks a lot.

**Comment by belangeo** [comment]
If you don't mind drawing the waveform in a table, you can use OscTrig, which take a trigger to reset the phase to zero. Something like this:

```
notes = Notein(poly=10, scale=0, first=0, last=127, channel=0, mul=1)

t = SawTable(order=20)

freqs = MToF(notes["pitch"])
env = MidiAdsr(notes['velocity'])
lfo = OscTrig(t, notes["trigon"], freq=freqs, mul=env)
lfo2 = OscTrig(t, notes["trigon"], freq=freqs * (1 + 0.0052), mul=env * (6./7))
lfo3 = OscTrig(t, notes["trigon"], freq=freqs * (1 + 0.0102), mul=env * (3./4))
mix = Mix([lfo, lfo2, lfo3], voices=1, mul=0.1).out()
```

Otherwise, the LFO object has a `reset()` method, but if you want to use it, you'll have to call a function from a MIDI noteon and do all the stuff (change frequencies, reset the phases and start the envelope) in there. Not as easy as using OscTrig!

**Comment by belangeo** [comment]
Closing as not an issue.
