### ISSUE TITLE
In the last built _.ctrl() does not work properly on macOS

### ISSUE THREAD

**Issue by Bibiko** [belangeo/pyo#254]
I've just built the pyo package on macOS (13.1 arm and 10.4 intel) with the current version successfully (by fixing self.pos issue) but _.ctrl() does not work correctly. To reproduce run for instance pyo/examples/03-generators/02-band-limited-oscs.py; after start a sound is produced but the LFO controls `freq` and `mul` do not work. If you change e.g. `freq` the sound does not change unless you close the control window.

**Comment by belangeo** [comment]
Yes, I just found the root cause... It's fixed in master.

**Comment by Bibiko** [comment]
Thanks - it works on macOS. I didn't realise it was related to the new get, int and float methods.

**Comment by belangeo** [comment]
I didn't too when I worked on it, but it makes sense as almost all parameters can be a number *or* a PyoObject, it's tricky to implement the number protocol as part of the PyoObject. I don't want to fix this right now because releasing for 3.10 and 3.11 is the priority, but I kept the patch to get back to it after the release!
